
- name: copy the install_k3s.sh script to the remote host
  copy:
    src: install_k3s.sh
    dest: /usr/local/bin/install_k3s.sh
    mode: 0755
  tags:
    - k3s

- name: run the install_k3s.sh script for a server if k3s_join_url is not defined
  shell: "K3_STOKEN={{k3s_token}} /usr/local/bin/install_k3s.sh server --cluster-init --token {{k3s_token}} --disable servicelb"
  args:
      creates: "/usr/local/bin/k3s"
  when: k3s_join_url is not defined
  tags:
    - k3s


- name: run the install_k3s.sh script for a server and join it if k3s_join_url is defined
  shell: "K3_STOKEN={{k3s_token}} /usr/local/bin/install_k3s.sh server --token {{k3s_token}} --server {{k3s_join_url}} --disable servicelb" 
  args:
      creates: "/usr/local/bin/k3s"
  when: k3s_join_url is defined 
  tags:
    - k3s


- name: Deploy metallb template file to the remote host
  template:
    src: metallb-config.yaml.j2
    dest: /etc/k3s/metallb-config.yaml
  when: metallb_ip_range is defined
  tags:
    - k3s 